### ISSUE TITLE
GRPCSTTBackground распознает запись воспроизводимую через PlayBackground

### ISSUE THREAD

**Issue by DmitriyAnokhin** [TinkoffCreditSystems/asterisk-voicekit-modules#4]
Приветствую.

По-моему это баг.
GRPCSTTBackground распознает запись воспроизводимую через PlayBackground.

Насколько я понимаю GRPCSTTBackground должен распознавать только аудиопоток абонента.

Asterisk 16.12.0

**Comment by g-e-okopnik** [comment]
Приветствую.

Не удалось воспроизвести (прошу прощения за абсурдно медленную реакцию).

Могу попробовать посмотреть на вашем хосте (есть такая возможность).
Либо нужно как-то локализовать настройки dialplan'а, которые позволять воспроизвести ситуацию (проще всего через Dockerfile).
