### ISSUE TITLE
После загрузки модулей в Asterisk ошибки

### ISSUE THREAD

**Issue by sd166** [TinkoffCreditSystems/asterisk-voicekit-modules#7]
Добрый день.
После сборки модулей и загрузки их в Asterisk. Сначала ругается на XML Документацию, но работе не мешает.

Дальше при попытке воспользоваться данным примером https://github.com/TinkoffCreditSystems/asterisk-voicekit-modules/blob/v1.4.7/examples/combined/combined_stt_tts/etc/asterisk/extensions.ael

в консоли Asterisk выводится: 

grpc_stt.cpp:650 void grpc_stt_run(int, const char*, const char*, const char*, const char*, const char*, const char*, ast_channel*, int, const char*, const char*, int, grpc_stt_frame_format, int, double, double, double, double, double, int, double): GRPC STT finished with error (code = 16): signature validation failed

app_playbackground.c:459 stream_error_callback: GRPC TTS stream finished with error (code = 16): signature validation failed

Смотрел на подпись, вроде бы AST_BUILDOPT_SUM есть в собранных модулях.

Подскажите в какую сторону смотреть?

**Comment by sd166** [comment]
Кто нибудь сталкивался с данной проблемой? Есть ли решение?

**Comment by g-e-okopnik** [comment]
Добрый день!
Кажается, что модули при сборке смотрели не на тот Asterisk, в который были установлены.
Подробнее могу разобраться только если непосредственно схожу на машинку.
Напишите сюда, пожалуйста: https://t.me/hc_guy - оперативнее отвечу.

**Comment by sd166** [comment]
Решили проблему. Спасибо за это @g-e-okopnik. 
На самом деле проблема была в неверно указанном secret-key в конфигурационных файлах. 
После исправления reload не помог. Пришлось сделать restart asterisk
